{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 1\n  -4\n  +1", "trace": "@pytest.mark.first\n    def test_02():\n        print('test02')\n>       assert(4==1)\nE       assert 4 == 1\nE         -4\nE         +1\n\ntest_order.py:11: AssertionError"}, "attachments": [{"name": "log", "source": "489a4cc0-9138-4208-93c7-e69bcffc8b6e-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "87a87fef-b986-48f1-904d-97f5788ebd6c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9d5ed948-5bec-4f4a-8742-183f46213363-attachment.txt", "type": "text/plain"}], "start": 1551342395413, "stop": 1551342395414, "uuid": "54666d06-a4ea-4fe2-8b39-37202a9f16c6", "historyId": "077cdda3ea6949dec56d3e7fe9dc3598", "fullName": "test_order#test_02", "labels": [{"name": "tag", "value": "first"}, {"name": "suite", "value": "test_order"}, {"name": "host", "value": "lizdeMacBook-Air.local"}, {"name": "thread", "value": "2744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_order"}]}